### ISSUE TITLE
Save token on local storage then loginWithToken ?

### ISSUE THREAD

**Issue by hems** [Gregivy/simpleddp-plugin-login#6]
Hello, I'm wondering if this plugin or simpleddp itself can save the login response on localStorage and then if the user refreshes the page automatically call login again using the localStorage token?

**Comment by smartgamer** [comment]
Hi,

When I try to use login with email, it failed. Login only works when using username only.

let userAuth = await server.login({
  password,
  user: {
      username,
      email
  }
});

any fix for this?

**Comment by hems** [comment]
@smartgamer this issue isn't about login, I believe you should create another issue.

**Comment by Gregivy** [comment]
Hi, this plugin and simpleDDP is platform agnostic and `localStorage` or anything like that was not included by design because simpleDDP can be used in different environments like node.js, browser or a mobile app (like ReactNative). So it's up to developer to make login persistent if he needs that with the appropriate tools he has in his project.

**Comment by hems** [comment]
all good @Gregivy! thanks a lot.

from reading the source code i gather that to resume with a token you need to call "resume: token, false" as the parameters, right?

https://github.com/Gregivy/simpleddp-plugin-login/blob/4.x.x/src/main.js#L55-L62

i think that will do ( :

**Comment by Gregivy** [comment]
You actually won't need to use token, but if you really want to
```js
await server.login({resume:'your_token_here'})
```

**Comment by hems** [comment]
Yes thanks!

I now using https://github.com/nbubna/store to store the auth and then calling `resume` when needed.
